### PR TITLE
remove duplicated tasks bar component #75

### PR DESCRIPTION
**Pull request by mniegrzybowska**

### CODE REVIEW

**Comment by miniMax18** [comment]
someChallenge
After the first quick look I have seen that (after checkout to this f274e49 PR branch). I guess this is not what We want. I check it for solution.

**Comment by mniegrzybowska** [comment]
@miniMax18 fixed :) take a look now

**Comment by miniMax18** [comment]
This is legit right now 👍 well done @mniegrzybowska and @katarzynaFronc 🥇

**Comment by mniegrzybowska** [comment]
can you approve so that we can merge @miniMax18 ?

**Review by miniMax18 — APPROVED** [review]
👍

**Pull request merged**
